CREATE TABLE MEMBER (
	MID VARCHAR2(20) PRIMARY KEY
	, PASSWORD VARCHAR2(20) NOT NULL
	, NAME VARCHAR2(30) NOT NULL
	, ROLE VARCHAR2(10) DEFAULT 'USER'
);

SELECT * FROM MEMBER;

DROP TABLE MEMBER;

INSERT INTO MEMBER(MID, PASSWORD, NAME, ROLE) VALUES('admin', '1234', '관리자', 'ADMIN');


UPDATE "MEMBER" SET NAME = ? WHERE MID = ?



CREATE TABLE PRODUCT (
	NUM NUMBER PRIMARY KEY
	, NAME VARCHAR2(50) NOT NULL
	, DETAILS VARCHAR2(100)
	, PRICE NUMBER
	, CNT NUMBER
	, SELLER VARCHAR2(20) NOT NULL
);

SELECT * FROM PRODUCT;

DROP TABLE PRODUCT;

INSERT INTO PRODUCT 
VALUES((SELECT NVL(MAX(NUM)+1,0) FROM PRODUCT), '사이다', '톡쏘는 칠성사이다', 1200, 5, 'admin');
INSERT INTO PRODUCT 
VALUES((SELECT NVL(MAX(NUM)+1,0) FROM PRODUCT), '콜라', '톡쏘는 코카콜라', 1300, 2, 'admin');
INSERT INTO PRODUCT 
VALUES((SELECT NVL(MAX(NUM)+1,0) FROM PRODUCT), '망고 스무디', '달달한 망고 스무디', 3000, 0, 'admin');

